spring.datasource.url=jdbc:postgresql://localhost:5432/lms_bd
spring.datasource.username=postgres
spring.datasource.password=Balu88552200

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.default-student-password=student123

# Enable Spring Security debug logging
logging.level.org.springframework.security=DEBUG

face.recognition.threshold=0.55

# Cloudinary configuration for attendance evidence uploads
cloudinary.cloud-name=dzzg0jtcc
cloudinary.api-key=567571857691239
cloudinary.api-secret=E2WdzQGxN5Bk6EzmJsBxbMYaNxA
