CREATE TABLE IF NOT EXISTS attendance_evidence (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url VARCHAR(1024) NOT NULL,
  public_id VARCHAR(512) NOT NULL,
  captured_at TIMESTAMP NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  attendance_session_id VARCHAR(128),
  teacher_id BIGINT NOT NULL,
  CONSTRAINT fk_attendance_evidence_teacher FOREIGN KEY (teacher_id) REFERENCES users(id)
);
